### ISSUE TITLE
Windows not supported

### ISSUE THREAD

**Issue by otakot** [jorisroovers/gitlint#20]
When trying to install on windows 7 with python 2.7.11 - I got following error trace: 

```
Collecting gitlint
  Using cached gitlint-0.8.0-py2.py3-none-any.whl
Collecting sh==1.11 (from gitlint)
  Using cached sh-1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-q_3wmy\sh\setup.py", line 4, in <module>
        import sh
      File "sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-q_3wmy\sh\
```

Installation of pbs 0.110 did not help to resolve the issue - same error occurs

**Comment by jorisroovers** [comment]
gitlint currently doesn't support Windows. No concrete plans either, might be something for the future.

**Comment by otakot** [comment]
thanks

**Comment by jorisroovers** [comment]
Keeping this open, as we might still consider this in the future.

**Comment by Kristinita** [comment]
> gitlint currently doesn't support Windows. 

@jorisroovers , I think, it would be nice, if you will show it at the beginning of README and documentation, that Windows users do not waste their time.

Thanks.

**Comment by jorisroovers** [comment]
Made some time to work on this a bit. Relevant commits: cc5e6d8da25ddbd9f3ac302f22d688dca38e62c4 and 20ac439ce94a1ba2628bb21f5e8621de398398e3.

I'm not a Windows user myself, but from the basic testing I did on a Windows 10 VM using Python 2.7 and Python 3.7, basic linting functionality seems to work. I'd appreciate anyone doing additional testing to confirm its working and report any bugs they find. I've already merged this work into master.

Things that work:
```sh
# lint latest commit
gitlint
gitlint -v --ignore T3,T5 # Options seem to work too

# Pass a message via stdin
echo "WIP: foöbar" > gitlint
git log -1 --pretty=%B | gitlint

# Commit ranges
gitlint --commits HEAD~2^..HEAD
```

However, I've also found a number of issues (some worse than others):
https://github.com/jorisroovers/gitlint/issues?q=is%3Aissue+is%3Aopen+label%3Awindows

I'll be releasing this (marked as experimental) as part of the 0.12.0 release later this week.

**Comment by ttwister** [comment]
Hello,

I tried creating user-defined rules on a Windows host (using Git-Bash) and those are not discovered.
I have created a CommitRule _UC1_ based on one of your examples.

Do you experience the same behavior?
```sh
$ gitlint --debug --extra-path myextensions/rules.py
DEBUG: gitlint.cli To report issues, please visit https://github.com/jorisroovers/gitlint/issues
DEBUG: gitlint.cli Platform: Windows-10-10.0.17763
DEBUG: gitlint.cli Python version: 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]
DEBUG: gitlint.cli Git version: git version 2.18.0.windows.1
DEBUG: gitlint.cli Gitlint version: 0.12.0
DEBUG: gitlint.cli GITLINT_USE_SH_LIB: [NOT SET]
DEBUG: gitlint.cli Configuration
config-path: C:\Users\xyz\path\.gitlint
[GENERAL]
extra-path: C:\Users\xyz\path\myextensions\rules.py
contrib: [u'contrib-title-conventional-commits']
ignore:
ignore-merge-commits: True
ignore-fixup-commits: True
ignore-squash-commits: True
ignore-stdin: True
verbosity: 3
debug: True
target: C:\Users\xyz\path
[RULES]
  I1: ignore-by-title
     ignore=all
     regex=^Release(.*)
  I2: ignore-by-body
     ignore=all
     regex=None
  T1: title-max-length
     line-length=70
[...]
  CT1: contrib-title-conventional-commits
     types=build,ci,doc,feat,fix,perf,refactor,style,test
[...]
```
