### ISSUE TITLE
Cannot install gitlint vai pip

### ISSUE THREAD

**Issue by sakonachhoeurng** [jorisroovers/gitlint#36]
Hi,
I am looking for your supporting.
I have following error below:
OS: Ubuntu 16.04
Python version: 2.7.12
pip version: 9.0.1

After I run `pip install gitlint` there are following error below relate to permission.

```
Exception:
Traceback (most recent call last):
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/sakona/.local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/sh.py'
```
Thanks for your support and give suggestion.

**Comment by asottile** [comment]
You probably either want to use a virtualenv, or `pip install --local gitlint` -- as it is, it's trying to install globally on your system which requires root.

**Comment by jorisroovers** [comment]
Exactly what @asottile said :-) Closing this
